//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipWeb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdemePlaniTaksit
    {
        public int Id { get; set; }
        public Nullable<int> OdemePlaniId { get; set; }
        public Nullable<int> TaksitNo { get; set; }
        public Nullable<System.DateTime> TaksitTarihi { get; set; }
        public Nullable<decimal> TaksitTutari { get; set; }
    
        public virtual OdemePlani OdemePlani { get; set; }
    }
}
