//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipWeb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdemePlani
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OdemePlani()
        {
            this.OdemePlaniTaksit = new HashSet<OdemePlaniTaksit>();
        }
    
        public int Id { get; set; }
        public string MusteriNo { get; set; }
        public Nullable<bool> DurumKodu { get; set; }
        public Nullable<int> DosyaId { get; set; }
    
        public virtual TakipDosya TakipDosya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdemePlaniTaksit> OdemePlaniTaksit { get; set; }
    }
}
