//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipWeb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakipSurec
    {
        public int Id { get; set; }
        public string MusteriNo { get; set; }
        public Nullable<int> DosyaId { get; set; }
        public Nullable<int> SurecKodu { get; set; }
    
        public virtual TakipDosya TakipDosya { get; set; }
    }
}
