//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipWeb.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TakipDbEntities : DbContext
    {
        public TakipDbEntities()
            : base("name=TakipDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OdemePlani> OdemePlani { get; set; }
        public virtual DbSet<OdemePlaniTaksit> OdemePlaniTaksit { get; set; }
        public virtual DbSet<TakipDosya> TakipDosya { get; set; }
        public virtual DbSet<TakipSurec> TakipSurec { get; set; }
    }
}
