//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipWeb.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakipDosya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TakipDosya()
        {
            this.OdemePlani = new HashSet<OdemePlani>();
            this.TakipSurec = new HashSet<TakipSurec>();
        }
    
        public int Id { get; set; }
        public string SubeKodu { get; set; }
        public string MusteriNo { get; set; }
        public string BirimKodu { get; set; }
        public Nullable<System.DateTime> DosyaDurumTarihi { get; set; }
        public Nullable<int> IlKodu { get; set; }
        public Nullable<int> IlceKodu { get; set; }
        public Nullable<decimal> Borc { get; set; }
        public Nullable<decimal> TahsilTutari { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdemePlani> OdemePlani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakipSurec> TakipSurec { get; set; }
    }
}
